Point Of Sales v1.0
96boards-projects/pos pull request #1
Opened 2018-05-28 13:08 UTC by ric96

Signed-off-by: Sahaj Sarup <sahaj.sarup@linaro.org>

2018-05-28 13:19 UTC, Mani-Sadhasivam requested changes
Looks good! Just a small nitpick.

2018-05-28 13:19 UTC, Mani-Sadhasivam commented on README.md
> +- [Any 96Boards CE](https://www.96boards.org/products/ce/) x3
What does x3 mean? 3 boards? In that case use below:

[Any 96Boards CE](https://www.96boards.org/products/ce/) - 3 Nos

2018-06-04 05:04 UTC, ric96 commented
@Mani-Sadhasivam I made the requested changes...

2018-06-04 13:03 UTC, Mani-Sadhasivam requested changes

2018-06-04 13:03 UTC, Mani-Sadhasivam commented on README.md
> +- [Any 96Boards CE](https://www.96boards.org/products/ce/) 3 Nos
please mention the OS here

2018-06-04 13:16 UTC, Mani-Sadhasivam approved these changes

2018-06-04 13:17 UTC, merged